let a;
a = "5";
let b;
b = "10";
console.log("a + b is ", a + b);
console.log("a - b is ", a + b);
console.log("a / b is ", a + b);
console.log("a % b is ", a + b);
console.log("a ** b is ", a + b);
console.log("a ++ b is ", a + b);
console.log("a -- b is ", a + b);